services:
  - type: web
    name: fawna-hotel
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FOOD_SERVICE_IPV4
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        sync: false

  - type: pserv
    name: fawna-hotel-db
    env: postgresql
    plan: free
